btk: btkLabelPropagation.cxx File Reference
btkLabelPropagation.cxx File Reference
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 49 of file btkLabelPropagation.cxx.
References LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), Dimension, LabelFusionTool< T >::GetFuzzyWeightImage(), LabelFusionTool< T >::GetOutput(), LabelFusionTool< T >::GetWeightImage(), LabelFusionTool< T >::InitImage(), LabelFusionTool< T >::m_hwnImage, LabelFusionTool< T >::m_hwvsImage, LabelFusionTool< T >::ReadAnatomicalImages(), LabelFusionTool< T >::ReadInput(), LabelFusionTool< T >::ReadLabelImages(), LabelFusionTool< T >::ReadOneImage(), LabelFusionTool< T >::SetAggregationStrategy(), LabelFusionTool< T >::SetBlockwiseStrategy(), LabelFusionTool< T >::SetCentralPointStrategy(), LabelFusionTool< T >::SetLowerThresholds(), LabelFusionTool< T >::SetMaskImage(), LabelFusionTool< T >::SetMinLabel(), LabelFusionTool< T >::SetNormalizationStrategy(), LabelFusionTool< T >::SetOptimizationStrategy(), LabelFusionTool< T >::SetPaddingValue(), LabelFusionTool< T >::SetPatchSize(), LabelFusionTool< T >::SetSmoothing(), and LabelFusionTool< T >::SetSpatialBandwidth().