btk: btkODFStreamlineTractography.cxx File Reference
btkODFStreamlineTractography.cxx File Reference
Functions
Real ComputeGFA (SHModel *model, Signal *signal, Point p)
bool IsInsideMask (Point p, Mask::Pointer mask)
int main (int argc, char *argv[])
Direction MeanDirection (SHModel *modelFun, Point currentPoint, Direction lastDirection, Real angleThreshold)
Function Documentation
Real ComputeGFA (SHModel * model, Signal * signal, Point p)
Definition at line 151 of file btkODFStreamlineTractography.cxx.
References btk::SHModel::signalAt(), and btk::Signal::signalAt().
Referenced by main().
bool IsInsideMask (Point p, Mask::Pointer mask)
Definition at line 65 of file btkODFStreamlineTractography.cxx.
References btk::CartesianCoordinates::x(), btk::CartesianCoordinates::y(), and btk::CartesianCoordinates::z().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 179 of file btkODFStreamlineTractography.cxx.
References ComputeGFA(), Display1, Display2, btk::SHModelEstimator::estimate(), btk::SignalExtractor::extract(), btk::SignalExtractor::GetDirections(), btk::SignalExtractor::GetMask(), btk::SHModel::getMaxDirectionAt(), btk::SHModelEstimator::GetModel(), btk::GetRadixOf(), btk::SignalExtractor::GetSigmas(), btk::SignalExtractor::GetSignal(), IsInsideMask(), btk::Direction::isNull(), MeanDirection(), btk::SphericalCoordinates::phi(), btk::SHModelEstimator::save(), btk::SignalExtractor::save(), btk::SphericalCoordinates::theta(), btk::Direction::toVector(), btk::CartesianCoordinates::x(), btk::CartesianCoordinates::y(), and btk::CartesianCoordinates::z().
Direction MeanDirection (SHModel * modelFun, Point currentPoint, Direction lastDirection, Real angleThreshold)
Definition at line 84 of file btkODFStreamlineTractography.cxx.
References btk::SHModel::getMaxDirectionsAt(), btk::SHModel::odfAt(), btk::Direction::setNull(), btk::Direction::toVector(), btk::CartesianCoordinates::x(), btk::CartesianCoordinates::y(), and btk::CartesianCoordinates::z().
Referenced by main().