BTK: LabelFusionTool< T > Class Template Reference
LabelFusionTool< T > Class Template Reference
#include <btkLabelPropagationTool.h>
Public Types
typedef
itk::ImageRegionConstIterator
< itkFloatImage > itkFloatConstIterator
typedef itk::Image< float, 3 > itkFloatImage
typedef
itk::ImageRegionIterator
< itkFloatImage > itkFloatIterator
typedef
itk::ImageRegionIteratorWithIndex
< itkFloatImage > itkFloatIteratorWithIndex
typedef itkFloatImage::Pointer itkFloatPointer
typedef itk::Image< std::map
< T, float >, 3 > itkMapImage
typedef
itk::ImageRegionIterator
< itkMapImage > itkMapIterator
typedef itkMapImage::Pointer itkMapPointer
typedef
itk::ImageRegionConstIterator
< itkTImage > itkTConstIterator
typedef itk::ImageDuplicator
< itkTImage > itkTDuplicator
typedef itk::Image< T, 3 > itkTImage
typedef
itk::ImageRegionIterator
< itkTImage > itkTIterator
typedef
itk::ImageRegionIteratorWithIndex
< itkTImage > itkTIteratorWithIndex
typedef itkTImage::Pointer itkTPointer
typedef itk::ImageFileReader
< itkTImage > itkTReader
Public Member Functions
void AddFuzzyLabelPatchToLabelImage (typename itkTImage::IndexType p, itkTPointer &patch, std::vector< std::map< T, float > > &vectorMap)
void AddLabelPatchToLabelImage (typename itkTImage::IndexType p, itkTPointer &patch, double weight)
void AddPatchToImage (typename itkTImage::IndexType p, itkFloatPointer &patch, itkFloatPointer &image, itkFloatPointer &weightImage, double weight)
bool CheckSpeed (typename itkTImage::IndexType p, typename itkTImage::IndexType q, int i)
void ComputeDenoisedOutput ()
void ComputeOutput ()
void ComputeOutput_groupwise ()
void ComputePatchRegion (typename itkTImage::IndexType p, typename itkTImage::RegionType &imageRegion, typename itkTImage::RegionType &patchRegion)
void ComputeSearchRegion (typename itkTImage::IndexType p, typename itkTImage::RegionType &region)
void CreatePatch (itkMapPointer &patch)
void CreatePatch (itkTPointer &patch)
void CreatePatch (itkFloatPointer &patch)
void Get2Patches (typename itkTImage::IndexType p, itkTPointer &anatomicalPatch, itkTPointer &anatomicalImage, itkTPointer &labelPatch, itkTPointer &labelImage)
double GetDenoisedPatch (typename itkTImage::IndexType p, itkFloatPointer &patch)
void GetFuzzyLabelPatch (typename itkTImage::IndexType p, itkTPointer &patch, std::vector< std::map< T, float > > &vectorMap)
void GetFuzzyWeightImage (itkFloatPointer &outputImage, int label)
double GetLabelPatch (typename itkTImage::IndexType p, itkTPointer &patch)
double GetLabelPatchUsingNormalization (typename itkTImage::IndexType p, itkTPointer &patch)
void GetNormalizedPatch (typename itkTImage::IndexType p, itkFloatPointer &patch, itkTPointer &image, float mean, float stddev)
void GetOutput (itkTPointer &outputImage)
void GetPatch (typename itkTImage::IndexType p, itkTPointer &patch, itkTPointer &image)
void GetWeightImage (itkTPointer &outputImage)
void InitImage (itkFloatPointer &image)
double PatchDistance (itkTPointer &p, itkTPointer &q)
double PatchDistance (itkFloatPointer &p, itkFloatPointer &q)
void ReadAnatomicalImages (std::vector< std::string > &input_file)
void ReadInput (std::string input_file)
void ReadLabelImages (std::vector< std::string > &input_file)
void ReadOneImage (std::string input_file, itkTPointer &image)
void SetAggregationStrategy (int a)
void SetBlockwiseStrategy (int b)
void SetCentralPointStrategy (int s)
void SetLowerThresholds (float m, float v)
void SetMaskImage (itkTPointer maskImage)
void SetMinLabel (int l)
void SetNormalizationStrategy (int n)
void SetOptimizationStrategy (int o)
void SetPaddingValue (float padding)
void SetPatchSize (int h)
void SetSmoothing (float beta)
void SetSpatialBandwidth (int s)
Public Attributes
int m_aggregation
std::vector< itkTPointer > m_anatomicalImages
int m_blockwise
int m_centralPointStrategy
itkTImage::SizeType m_fullPatchSize
itkTImage::SizeType m_fullSpatialBandwidth
itkTImage::SizeType m_halfPatchSize
itkTImage::SizeType m_halfSpatialBandwidth
itkTPointer m_hwnImage
itkTPointer m_hwvsImage
itkTPointer m_inputImage
itkMapPointer m_labelFusionImage
std::vector< itkTPointer > m_labelImages
float m_lowerMeanThreshold
float m_lowerVarianceThreshold
itkTPointer m_maskImage
std::vector< itkFloatPointer > m_meanAnatomicalImages
itkFloatPointer m_meanImage
int m_minLabel
int m_normalization
int m_optimized
itkTPointer m_outputImage
float m_padding
float m_rangeBandwidth
itkTImage::RegionType m_region
itkTImage::SizeType m_size
itkTImage::SpacingType m_spacing
std::vector< itkFloatPointer > m_varianceAnatomicalImages
itkFloatPointer m_varianceImage
itkFloatPointer m_weightImage
Detailed Description
template<typename T>
class LabelFusionTool< T >
Definition at line 55 of file btkLabelPropagationTool.h.
Member Typedef Documentation
template<typename T > typedef itk::ImageRegionConstIterator< itkFloatImage > LabelFusionTool< T >::itkFloatConstIterator
Definition at line 69 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::Image< float, 3> LabelFusionTool< T >::itkFloatImage
Definition at line 66 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageRegionIterator< itkFloatImage > LabelFusionTool< T >::itkFloatIterator
Definition at line 68 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageRegionIteratorWithIndex< itkFloatImage > LabelFusionTool< T >::itkFloatIteratorWithIndex
Definition at line 70 of file btkLabelPropagationTool.h.
template<typename T > typedef itkFloatImage::Pointer LabelFusionTool< T >::itkFloatPointer
Definition at line 67 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::Image< std::map<T, float>, 3> LabelFusionTool< T >::itkMapImage
Definition at line 72 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageRegionIterator< itkMapImage > LabelFusionTool< T >::itkMapIterator
Definition at line 74 of file btkLabelPropagationTool.h.
template<typename T > typedef itkMapImage::Pointer LabelFusionTool< T >::itkMapPointer
Definition at line 73 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageRegionConstIterator< itkTImage > LabelFusionTool< T >::itkTConstIterator
Definition at line 62 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageDuplicator< itkTImage > LabelFusionTool< T >::itkTDuplicator
Definition at line 60 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::Image< T, 3> LabelFusionTool< T >::itkTImage
Definition at line 58 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageRegionIterator< itkTImage > LabelFusionTool< T >::itkTIterator
Definition at line 61 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageRegionIteratorWithIndex< itkTImage > LabelFusionTool< T >::itkTIteratorWithIndex
Definition at line 63 of file btkLabelPropagationTool.h.
template<typename T > typedef itkTImage::Pointer LabelFusionTool< T >::itkTPointer
Definition at line 59 of file btkLabelPropagationTool.h.
template<typename T > typedef itk::ImageFileReader< itkTImage > LabelFusionTool< T >::itkTReader
Definition at line 64 of file btkLabelPropagationTool.h.
Member Function Documentation
template<typename T > void LabelFusionTool< T >::AddFuzzyLabelPatchToLabelImage (typename itkTImage::IndexType p, itkTPointer & patch, std::vector< std::map< T, float > > & vectorMap)
Definition at line 1522 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::ComputePatchRegion(), and LabelFusionTool< T >::m_labelFusionImage.
Referenced by LabelFusionTool< T >::ComputeOutput_groupwise().
template<typename T > void LabelFusionTool< T >::AddLabelPatchToLabelImage (typename itkTImage::IndexType p, itkTPointer & patch, double weight)
Definition at line 1501 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::ComputePatchRegion(), and LabelFusionTool< T >::m_labelFusionImage.
Referenced by LabelFusionTool< T >::ComputeOutput().
template<typename T > void LabelFusionTool< T >::AddPatchToImage (typename itkTImage::IndexType p, itkFloatPointer & patch, itkFloatPointer & image, itkFloatPointer & weightImage, double weight)
Definition at line 1256 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::ComputePatchRegion().
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput().
template<typename T > bool LabelFusionTool< T >::CheckSpeed (typename itkTImage::IndexType p, typename itkTImage::IndexType q, int i)
Definition at line 736 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_lowerMeanThreshold, LabelFusionTool< T >::m_lowerVarianceThreshold, LabelFusionTool< T >::m_meanAnatomicalImages, LabelFusionTool< T >::m_meanImage, LabelFusionTool< T >::m_varianceAnatomicalImages, and LabelFusionTool< T >::m_varianceImage.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), and LabelFusionTool< T >::GetLabelPatchUsingNormalization().
template<typename T > void LabelFusionTool< T >::ComputeDenoisedOutput ()
Definition at line 1037 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::AddPatchToImage(), LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::m_aggregation, LabelFusionTool< T >::m_blockwise, LabelFusionTool< T >::m_halfPatchSize, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_maskImage, LabelFusionTool< T >::m_outputImage, LabelFusionTool< T >::m_size, and LabelFusionTool< T >::m_weightImage.
template<typename T > void LabelFusionTool< T >::ComputeOutput ()
Definition at line 770 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::AddLabelPatchToLabelImage(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), LabelFusionTool< T >::m_aggregation, LabelFusionTool< T >::m_blockwise, LabelFusionTool< T >::m_halfPatchSize, LabelFusionTool< T >::m_labelFusionImage, LabelFusionTool< T >::m_maskImage, LabelFusionTool< T >::m_minLabel, LabelFusionTool< T >::m_normalization, LabelFusionTool< T >::m_outputImage, LabelFusionTool< T >::m_size, and LabelFusionTool< T >::m_weightImage.
template<typename T > void LabelFusionTool< T >::ComputeOutput_groupwise ()
Definition at line 906 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::AddFuzzyLabelPatchToLabelImage(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), LabelFusionTool< T >::m_blockwise, LabelFusionTool< T >::m_halfPatchSize, LabelFusionTool< T >::m_labelFusionImage, LabelFusionTool< T >::m_maskImage, LabelFusionTool< T >::m_minLabel, LabelFusionTool< T >::m_normalization, LabelFusionTool< T >::m_outputImage, LabelFusionTool< T >::m_size, and LabelFusionTool< T >::m_weightImage.
template<typename T > void LabelFusionTool< T >::ComputePatchRegion (typename itkTImage::IndexType p, typename itkTImage::RegionType & imageRegion, typename itkTImage::RegionType & patchRegion)
Definition at line 657 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullPatchSize, LabelFusionTool< T >::m_halfPatchSize, and LabelFusionTool< T >::m_size.
Referenced by LabelFusionTool< T >::AddFuzzyLabelPatchToLabelImage(), LabelFusionTool< T >::AddLabelPatchToLabelImage(), LabelFusionTool< T >::AddPatchToImage(), LabelFusionTool< T >::Get2Patches(), LabelFusionTool< T >::GetNormalizedPatch(), and LabelFusionTool< T >::GetPatch().
template<typename T > void LabelFusionTool< T >::ComputeSearchRegion (typename itkTImage::IndexType p, typename itkTImage::RegionType & region)
Definition at line 694 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullSpatialBandwidth, LabelFusionTool< T >::m_halfSpatialBandwidth, and LabelFusionTool< T >::m_size.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), and LabelFusionTool< T >::GetLabelPatchUsingNormalization().
template<typename T > void LabelFusionTool< T >::CreatePatch (itkMapPointer & patch)
Definition at line 584 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullPatchSize.
template<typename T > void LabelFusionTool< T >::CreatePatch (itkTPointer & patch)
Definition at line 559 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullPatchSize.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > void LabelFusionTool< T >::CreatePatch (itkFloatPointer & patch)
Definition at line 572 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullPatchSize.
template<typename T > void LabelFusionTool< T >::Get2Patches (typename itkTImage::IndexType p, itkTPointer & anatomicalPatch, itkTPointer & anatomicalImage, itkTPointer & labelPatch, itkTPointer & labelImage)
Definition at line 634 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::ComputePatchRegion().
Referenced by LabelFusionTool< T >::GetFuzzyLabelPatch(), and LabelFusionTool< T >::GetLabelPatch().
template<typename T > double LabelFusionTool< T >::GetDenoisedPatch (typename itkTImage::IndexType p, itkFloatPointer & patch)
Definition at line 1150 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::ComputeSearchRegion(), LabelFusionTool< T >::CreatePatch(), LabelFusionTool< T >::GetNormalizedPatch(), LabelFusionTool< T >::GetPatch(), LabelFusionTool< T >::m_anatomicalImages, LabelFusionTool< T >::m_centralPointStrategy, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_meanAnatomicalImages, LabelFusionTool< T >::m_meanImage, LabelFusionTool< T >::m_optimized, LabelFusionTool< T >::m_rangeBandwidth, LabelFusionTool< T >::m_varianceAnatomicalImages, LabelFusionTool< T >::m_varianceImage, and LabelFusionTool< T >::PatchDistance().
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput().
template<typename T > void LabelFusionTool< T >::GetFuzzyLabelPatch (typename itkTImage::IndexType p, itkTPointer & patch, std::vector< std::map< T, float > > & vectorMap)
Definition at line 1356 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::ComputeSearchRegion(), LabelFusionTool< T >::CreatePatch(), LabelFusionTool< T >::Get2Patches(), LabelFusionTool< T >::GetPatch(), LabelFusionTool< T >::m_anatomicalImages, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_labelImages, LabelFusionTool< T >::m_optimized, LabelFusionTool< T >::m_rangeBandwidth, and LabelFusionTool< T >::PatchDistance().
Referenced by LabelFusionTool< T >::ComputeOutput_groupwise().
template<typename T > void LabelFusionTool< T >::GetFuzzyWeightImage (itkFloatPointer & outputImage, int label)
Definition at line 1596 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_labelFusionImage.
template<typename T > double LabelFusionTool< T >::GetLabelPatch (typename itkTImage::IndexType p, itkTPointer & patch)
Definition at line 1275 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::ComputeSearchRegion(), LabelFusionTool< T >::CreatePatch(), LabelFusionTool< T >::Get2Patches(), LabelFusionTool< T >::GetPatch(), LabelFusionTool< T >::m_anatomicalImages, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_labelImages, LabelFusionTool< T >::m_optimized, LabelFusionTool< T >::m_rangeBandwidth, and LabelFusionTool< T >::PatchDistance().
Referenced by LabelFusionTool< T >::ComputeOutput(), and LabelFusionTool< T >::ComputeOutput_groupwise().
template<typename T > double LabelFusionTool< T >::GetLabelPatchUsingNormalization (typename itkTImage::IndexType p, itkTPointer & patch)
Definition at line 1416 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::ComputeSearchRegion(), LabelFusionTool< T >::CreatePatch(), LabelFusionTool< T >::GetNormalizedPatch(), LabelFusionTool< T >::GetPatch(), LabelFusionTool< T >::m_anatomicalImages, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_labelImages, LabelFusionTool< T >::m_meanAnatomicalImages, LabelFusionTool< T >::m_meanImage, LabelFusionTool< T >::m_optimized, LabelFusionTool< T >::m_rangeBandwidth, LabelFusionTool< T >::m_varianceAnatomicalImages, LabelFusionTool< T >::m_varianceImage, and LabelFusionTool< T >::PatchDistance().
Referenced by LabelFusionTool< T >::ComputeOutput(), and LabelFusionTool< T >::ComputeOutput_groupwise().
template<typename T > void LabelFusionTool< T >::GetNormalizedPatch (typename itkTImage::IndexType p, itkFloatPointer & patch, itkTPointer & image, float mean, float stddev)
Definition at line 613 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::ComputePatchRegion().
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), and LabelFusionTool< T >::GetLabelPatchUsingNormalization().
template<typename T > void LabelFusionTool< T >::GetOutput (itkTPointer & outputImage)
Definition at line 1578 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_outputImage.
template<typename T > void LabelFusionTool< T >::GetPatch (typename itkTImage::IndexType p, itkTPointer & patch, itkTPointer & image)
Definition at line 595 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::ComputePatchRegion().
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > void LabelFusionTool< T >::GetWeightImage (itkTPointer & outputImage)
Definition at line 1584 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_weightImage.
template<typename T > void LabelFusionTool< T >::InitImage (itkFloatPointer & image)
Definition at line 724 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_inputImage.
Referenced by LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > double LabelFusionTool< T >::PatchDistance (itkTPointer & p, itkTPointer & q)
Definition at line 1548 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), and LabelFusionTool< T >::GetLabelPatchUsingNormalization().
template<typename T > double LabelFusionTool< T >::PatchDistance (itkFloatPointer & p, itkFloatPointer & q)
Definition at line 1563 of file btkLabelPropagationTool.h.
template<typename T > void LabelFusionTool< T >::ReadAnatomicalImages (std::vector< std::string > & input_file)
Definition at line 196 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_anatomicalImages, LabelFusionTool< T >::m_size, and LabelFusionTool< T >::m_spacing.
template<typename T > void LabelFusionTool< T >::ReadInput (std::string input_file)
Definition at line 163 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_labelFusionImage, LabelFusionTool< T >::m_outputImage, LabelFusionTool< T >::m_region, LabelFusionTool< T >::m_size, LabelFusionTool< T >::m_spacing, and LabelFusionTool< T >::m_weightImage.
template<typename T > void LabelFusionTool< T >::ReadLabelImages (std::vector< std::string > & input_file)
Definition at line 241 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_labelImages, LabelFusionTool< T >::m_size, and LabelFusionTool< T >::m_spacing.
template<typename T > void LabelFusionTool< T >::ReadOneImage (std::string input_file, itkTPointer & image)
Definition at line 1618 of file btkLabelPropagationTool.h.
template<typename T > void LabelFusionTool< T >::SetAggregationStrategy (int a)
Definition at line 453 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_aggregation.
template<typename T > void LabelFusionTool< T >::SetBlockwiseStrategy (int b)
Definition at line 447 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_blockwise.
template<typename T > void LabelFusionTool< T >::SetCentralPointStrategy (int s)
Definition at line 441 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_centralPointStrategy.
template<typename T > void LabelFusionTool< T >::SetLowerThresholds (float m, float v)
Definition at line 540 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_lowerMeanThreshold, and LabelFusionTool< T >::m_lowerVarianceThreshold.
template<typename T > void LabelFusionTool< T >::SetMaskImage (itkTPointer maskImage)
Definition at line 311 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_maskImage, LabelFusionTool< T >::m_region, LabelFusionTool< T >::m_size, and LabelFusionTool< T >::m_spacing.
template<typename T > void LabelFusionTool< T >::SetMinLabel (int l)
Definition at line 553 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_minLabel.
template<typename T > void LabelFusionTool< T >::SetNormalizationStrategy (int n)
Definition at line 547 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_normalization.
template<typename T > void LabelFusionTool< T >::SetOptimizationStrategy (int o)
Definition at line 459 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::CreatePatch(), LabelFusionTool< T >::GetPatch(), LabelFusionTool< T >::InitImage(), LabelFusionTool< T >::m_anatomicalImages, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_maskImage, LabelFusionTool< T >::m_meanAnatomicalImages, LabelFusionTool< T >::m_meanImage, LabelFusionTool< T >::m_optimized, LabelFusionTool< T >::m_size, LabelFusionTool< T >::m_varianceAnatomicalImages, and LabelFusionTool< T >::m_varianceImage.
template<typename T > void LabelFusionTool< T >::SetPaddingValue (float padding)
Definition at line 286 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_maskImage, and LabelFusionTool< T >::m_padding.
template<typename T > void LabelFusionTool< T >::SetPatchSize (int h)
Definition at line 345 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullPatchSize, LabelFusionTool< T >::m_halfPatchSize, and LabelFusionTool< T >::m_spacing.
template<typename T > void LabelFusionTool< T >::SetSmoothing (float beta)
Definition at line 381 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_halfPatchSize, LabelFusionTool< T >::m_inputImage, LabelFusionTool< T >::m_maskImage, LabelFusionTool< T >::m_rangeBandwidth, and LabelFusionTool< T >::m_size.
template<typename T > void LabelFusionTool< T >::SetSpatialBandwidth (int s)
Definition at line 363 of file btkLabelPropagationTool.h.
References LabelFusionTool< T >::m_fullSpatialBandwidth, LabelFusionTool< T >::m_halfSpatialBandwidth, and LabelFusionTool< T >::m_spacing.
Member Data Documentation
template<typename T > int LabelFusionTool< T >::m_aggregation
Definition at line 96 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), and LabelFusionTool< T >::SetAggregationStrategy().
template<typename T > std::vector<itkTPointer> LabelFusionTool< T >::m_anatomicalImages
Definition at line 84 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), LabelFusionTool< T >::ReadAnatomicalImages(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > int LabelFusionTool< T >::m_blockwise
Definition at line 91 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), and LabelFusionTool< T >::SetBlockwiseStrategy().
template<typename T > int LabelFusionTool< T >::m_centralPointStrategy
Definition at line 93 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), and LabelFusionTool< T >::SetCentralPointStrategy().
template<typename T > itkTImage::SizeType LabelFusionTool< T >::m_fullPatchSize
Definition at line 101 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputePatchRegion(), LabelFusionTool< T >::CreatePatch(), and LabelFusionTool< T >::SetPatchSize().
template<typename T > itkTImage::SizeType LabelFusionTool< T >::m_fullSpatialBandwidth
Definition at line 103 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeSearchRegion(), and LabelFusionTool< T >::SetSpatialBandwidth().
template<typename T > itkTImage::SizeType LabelFusionTool< T >::m_halfPatchSize
Definition at line 100 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), LabelFusionTool< T >::ComputePatchRegion(), LabelFusionTool< T >::SetPatchSize(), and LabelFusionTool< T >::SetSmoothing().
template<typename T > itkTImage::SizeType LabelFusionTool< T >::m_halfSpatialBandwidth
Definition at line 102 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeSearchRegion(), and LabelFusionTool< T >::SetSpatialBandwidth().
template<typename T > itkTPointer LabelFusionTool< T >::m_hwnImage
Definition at line 105 of file btkLabelPropagationTool.h.
template<typename T > itkTPointer LabelFusionTool< T >::m_hwvsImage
Definition at line 106 of file btkLabelPropagationTool.h.
template<typename T > itkTPointer LabelFusionTool< T >::m_inputImage
Definition at line 76 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), LabelFusionTool< T >::InitImage(), LabelFusionTool< T >::ReadInput(), LabelFusionTool< T >::SetOptimizationStrategy(), LabelFusionTool< T >::SetPaddingValue(), and LabelFusionTool< T >::SetSmoothing().
template<typename T > itkMapPointer LabelFusionTool< T >::m_labelFusionImage
Definition at line 78 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::AddFuzzyLabelPatchToLabelImage(), LabelFusionTool< T >::AddLabelPatchToLabelImage(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), LabelFusionTool< T >::GetFuzzyWeightImage(), and LabelFusionTool< T >::ReadInput().
template<typename T > std::vector<itkTPointer> LabelFusionTool< T >::m_labelImages
Definition at line 85 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::ReadLabelImages().
template<typename T > float LabelFusionTool< T >::m_lowerMeanThreshold
Definition at line 94 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::CheckSpeed(), and LabelFusionTool< T >::SetLowerThresholds().
template<typename T > float LabelFusionTool< T >::m_lowerVarianceThreshold
Definition at line 95 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::CheckSpeed(), and LabelFusionTool< T >::SetLowerThresholds().
template<typename T > itkTPointer LabelFusionTool< T >::m_maskImage
Definition at line 79 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), LabelFusionTool< T >::SetMaskImage(), LabelFusionTool< T >::SetOptimizationStrategy(), LabelFusionTool< T >::SetPaddingValue(), and LabelFusionTool< T >::SetSmoothing().
template<typename T > std::vector<itkFloatPointer> LabelFusionTool< T >::m_meanAnatomicalImages
Definition at line 86 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > itkFloatPointer LabelFusionTool< T >::m_meanImage
Definition at line 80 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > int LabelFusionTool< T >::m_minLabel
Definition at line 98 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), and LabelFusionTool< T >::SetMinLabel().
template<typename T > int LabelFusionTool< T >::m_normalization
Definition at line 97 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), and LabelFusionTool< T >::SetNormalizationStrategy().
template<typename T > int LabelFusionTool< T >::m_optimized
Definition at line 92 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > itkTPointer LabelFusionTool< T >::m_outputImage
Definition at line 77 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), LabelFusionTool< T >::GetOutput(), and LabelFusionTool< T >::ReadInput().
template<typename T > float LabelFusionTool< T >::m_padding
Definition at line 89 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::SetPaddingValue().
template<typename T > float LabelFusionTool< T >::m_rangeBandwidth
Definition at line 90 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetFuzzyLabelPatch(), LabelFusionTool< T >::GetLabelPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetSmoothing().
template<typename T > itkTImage::RegionType LabelFusionTool< T >::m_region
Definition at line 112 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ReadInput(), and LabelFusionTool< T >::SetMaskImage().
template<typename T > itkTImage::SizeType LabelFusionTool< T >::m_size
Definition at line 111 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), LabelFusionTool< T >::ComputePatchRegion(), LabelFusionTool< T >::ComputeSearchRegion(), LabelFusionTool< T >::ReadAnatomicalImages(), LabelFusionTool< T >::ReadInput(), LabelFusionTool< T >::ReadLabelImages(), LabelFusionTool< T >::SetMaskImage(), LabelFusionTool< T >::SetOptimizationStrategy(), and LabelFusionTool< T >::SetSmoothing().
template<typename T > itkTImage::SpacingType LabelFusionTool< T >::m_spacing
Definition at line 110 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ReadAnatomicalImages(), LabelFusionTool< T >::ReadInput(), LabelFusionTool< T >::ReadLabelImages(), LabelFusionTool< T >::SetMaskImage(), LabelFusionTool< T >::SetPatchSize(), and LabelFusionTool< T >::SetSpatialBandwidth().
template<typename T > std::vector<itkFloatPointer> LabelFusionTool< T >::m_varianceAnatomicalImages
Definition at line 87 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > itkFloatPointer LabelFusionTool< T >::m_varianceImage
Definition at line 81 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::CheckSpeed(), LabelFusionTool< T >::GetDenoisedPatch(), LabelFusionTool< T >::GetLabelPatchUsingNormalization(), and LabelFusionTool< T >::SetOptimizationStrategy().
template<typename T > itkFloatPointer LabelFusionTool< T >::m_weightImage
Definition at line 82 of file btkLabelPropagationTool.h.
Referenced by LabelFusionTool< T >::ComputeDenoisedOutput(), LabelFusionTool< T >::ComputeOutput(), LabelFusionTool< T >::ComputeOutput_groupwise(), LabelFusionTool< T >::GetWeightImage(), and LabelFusionTool< T >::ReadInput().
The documentation for this class was generated from the following file:
btkLabelPropagationTool.h