BTK: nr3.h File Reference
nr3.h File Reference
Classes
class NRMat3d< T >
class NRmatrix< T >
class NRvector< T >
Defines
#define throw(message) {printf("ERROR: %s\n in file %s at line %d\n", message,__FILE__,__LINE__); throw(1);}
Typedefs
typedef bool Bool
typedef char Char
typedef complex< double > Complex
typedef double Doub
typedef int Int
typedef long double Ldoub
typedef long long int Llong
typedef NRMat3d< Doub > Mat3DDoub
typedef const NRMat3d< Doub > Mat3DDoub_I
typedef NRMat3d< Doub > Mat3DDoub_IO
typedef NRMat3d< Doub > Mat3DDoub_O
typedef NRmatrix< Bool > MatBool
typedef const NRmatrix< Bool > MatBool_I
typedef NRmatrix< Bool > MatBool_IO
typedef NRmatrix< Bool > MatBool_O
typedef NRmatrix< Char > MatChar
typedef const NRmatrix< Char > MatChar_I
typedef NRmatrix< Char > MatChar_IO
typedef NRmatrix< Char > MatChar_O
typedef NRmatrix< Doub > MatDoub
typedef const NRmatrix< Doub > MatDoub_I
typedef NRmatrix< Doub > MatDoub_IO
typedef NRmatrix< Doub > MatDoub_O
typedef NRmatrix< Int > MatInt
typedef const NRmatrix< Int > MatInt_I
typedef NRmatrix< Int > MatInt_IO
typedef NRmatrix< Int > MatInt_O
typedef NRmatrix< Llong > MatLlong
typedef const NRmatrix< Llong > MatLlong_I
typedef NRmatrix< Llong > MatLlong_IO
typedef NRmatrix< Llong > MatLlong_O
typedef NRmatrix< Uchar > MatUchar
typedef const NRmatrix< Uchar > MatUchar_I
typedef NRmatrix< Uchar > MatUchar_IO
typedef NRmatrix< Uchar > MatUchar_O
typedef NRmatrix< Uint > MatUint
typedef const NRmatrix< Uint > MatUint_I
typedef NRmatrix< Uint > MatUint_IO
typedef NRmatrix< Uint > MatUint_O
typedef NRmatrix< Ullong > MatUllong
typedef const NRmatrix< Ullong > MatUllong_I
typedef NRmatrix< Ullong > MatUllong_IO
typedef NRmatrix< Ullong > MatUllong_O
typedef unsigned char Uchar
typedef unsigned int Uint
typedef unsigned long long int Ullong
typedef NRvector< Bool > VecBool
typedef const NRvector< Bool > VecBool_I
typedef NRvector< Bool > VecBool_IO
typedef NRvector< Bool > VecBool_O
typedef NRvector< Char > VecChar
typedef const NRvector< Char > VecChar_I
typedef NRvector< Char > VecChar_IO
typedef NRvector< Char > VecChar_O
typedef NRvector< Char * > VecCharp
typedef const NRvector< Char * > VecCharp_I
typedef NRvector< Char * > VecCharp_IO
typedef NRvector< Char * > VecCharp_O
typedef NRvector< Complex > VecComplex
typedef const NRvector< Complex > VecComplex_I
typedef NRvector< Complex > VecComplex_IO
typedef NRvector< Complex > VecComplex_O
typedef NRvector< Doub > VecDoub
typedef const NRvector< Doub > VecDoub_I
typedef NRvector< Doub > VecDoub_IO
typedef NRvector< Doub > VecDoub_O
typedef NRvector< Doub * > VecDoubp
typedef const NRvector< Doub * > VecDoubp_I
typedef NRvector< Doub * > VecDoubp_IO
typedef NRvector< Doub * > VecDoubp_O
typedef NRvector< Int > VecInt
typedef const NRvector< Int > VecInt_I
typedef NRvector< Int > VecInt_IO
typedef NRvector< Int > VecInt_O
typedef NRvector< Llong > VecLlong
typedef const NRvector< Llong > VecLlong_I
typedef NRvector< Llong > VecLlong_IO
typedef NRvector< Llong > VecLlong_O
typedef NRvector< Uchar > VecUchar
typedef const NRvector< Uchar > VecUchar_I
typedef NRvector< Uchar > VecUchar_IO
typedef NRvector< Uchar > VecUchar_O
typedef NRvector< Uint > VecUint
typedef const NRvector< Uint > VecUint_I
typedef NRvector< Uint > VecUint_IO
typedef NRvector< Uint > VecUint_O
typedef NRvector< Ullong > VecUllong
typedef const NRvector< Ullong > VecUllong_I
typedef NRvector< Ullong > VecUllong_IO
typedef NRvector< Ullong > VecUllong_O
Functions
template<class T >
const T & MAX (const T &a, const T &b)
float MAX (const float &a, const double &b)
float MAX (const double &a, const float &b)
template<class T >
const T & MIN (const T &a, const T &b)
float MIN (const double &a, const float &b)
float MIN (const float &a, const double &b)
float SIGN (const float &a, const double &b)
float SIGN (const double &a, const float &b)
template<class T >
T SIGN (const T &a, const T &b)
template<class T >
T SQR (const T a)
template<class T >
void SWAP (T &a, T &b)
Variables
static const Doub NaN = numeric_limits<Doub>::quiet_NaN()
Define Documentation
#define throw (message) {printf("ERROR: %s\n in file %s at line %d\n", message,__FILE__,__LINE__); throw(1);}
Definition at line 68 of file nr3.h.
Typedef Documentation
typedef bool Bool
Definition at line 489 of file nr3.h.
typedef char Char
Definition at line 481 of file nr3.h.
typedef complex<double> Complex
Definition at line 487 of file nr3.h.
typedef double Doub
Definition at line 484 of file nr3.h.
typedef int Int
Definition at line 470 of file nr3.h.
typedef long double Ldoub
Definition at line 485 of file nr3.h.
typedef long long int Llong
Definition at line 477 of file nr3.h.
typedef NRMat3d<Doub> Mat3DDoub
Definition at line 565 of file nr3.h.
typedef const NRMat3d<Doub> Mat3DDoub_I
Definition at line 564 of file nr3.h.
typedef NRMat3d<Doub> Mat3DDoub_IO
Definition at line 565 of file nr3.h.
typedef NRMat3d<Doub> Mat3DDoub_O
Definition at line 565 of file nr3.h.
typedef NRmatrix<Bool> MatBool
Definition at line 560 of file nr3.h.
typedef const NRmatrix<Bool> MatBool_I
Definition at line 559 of file nr3.h.
typedef NRmatrix<Bool> MatBool_IO
Definition at line 560 of file nr3.h.
typedef NRmatrix<Bool> MatBool_O
Definition at line 560 of file nr3.h.
typedef NRmatrix<Char> MatChar
Definition at line 551 of file nr3.h.
typedef const NRmatrix<Char> MatChar_I
Definition at line 550 of file nr3.h.
typedef NRmatrix<Char> MatChar_IO
Definition at line 551 of file nr3.h.
typedef NRmatrix<Char> MatChar_O
Definition at line 551 of file nr3.h.
typedef NRmatrix<Doub> MatDoub
Definition at line 557 of file nr3.h.
typedef const NRmatrix<Doub> MatDoub_I
Definition at line 556 of file nr3.h.
typedef NRmatrix<Doub> MatDoub_IO
Definition at line 557 of file nr3.h.
typedef NRmatrix<Doub> MatDoub_O
Definition at line 557 of file nr3.h.
typedef NRmatrix<Int> MatInt
Definition at line 539 of file nr3.h.
typedef const NRmatrix<Int> MatInt_I
Definition at line 538 of file nr3.h.
typedef NRmatrix<Int> MatInt_IO
Definition at line 539 of file nr3.h.
typedef NRmatrix<Int> MatInt_O
Definition at line 539 of file nr3.h.
typedef NRmatrix<Llong> MatLlong
Definition at line 545 of file nr3.h.
typedef const NRmatrix<Llong> MatLlong_I
Definition at line 544 of file nr3.h.
typedef NRmatrix<Llong> MatLlong_IO
Definition at line 545 of file nr3.h.
typedef NRmatrix<Llong> MatLlong_O
Definition at line 545 of file nr3.h.
typedef NRmatrix<Uchar> MatUchar
Definition at line 554 of file nr3.h.
typedef const NRmatrix<Uchar> MatUchar_I
Definition at line 553 of file nr3.h.
typedef NRmatrix<Uchar> MatUchar_IO
Definition at line 554 of file nr3.h.
typedef NRmatrix<Uchar> MatUchar_O
Definition at line 554 of file nr3.h.
typedef NRmatrix<Uint> MatUint
Definition at line 542 of file nr3.h.
typedef const NRmatrix<Uint> MatUint_I
Definition at line 541 of file nr3.h.
typedef NRmatrix<Uint> MatUint_IO
Definition at line 542 of file nr3.h.
typedef NRmatrix<Uint> MatUint_O
Definition at line 542 of file nr3.h.
typedef NRmatrix<Ullong> MatUllong
Definition at line 548 of file nr3.h.
typedef const NRmatrix<Ullong> MatUllong_I
Definition at line 547 of file nr3.h.
typedef NRmatrix<Ullong> MatUllong_IO
Definition at line 548 of file nr3.h.
typedef NRmatrix<Ullong> MatUllong_O
Definition at line 548 of file nr3.h.
typedef unsigned char Uchar
Definition at line 482 of file nr3.h.
typedef unsigned int Uint
Definition at line 471 of file nr3.h.
typedef unsigned long long int Ullong
Definition at line 478 of file nr3.h.
typedef NRvector<Bool> VecBool
Definition at line 534 of file nr3.h.
typedef const NRvector<Bool> VecBool_I
Definition at line 533 of file nr3.h.
typedef NRvector<Bool> VecBool_IO
Definition at line 534 of file nr3.h.
typedef NRvector<Bool> VecBool_O
Definition at line 534 of file nr3.h.
typedef NRvector<Char> VecChar
Definition at line 516 of file nr3.h.
typedef const NRvector<Char> VecChar_I
Definition at line 515 of file nr3.h.
typedef NRvector<Char> VecChar_IO
Definition at line 516 of file nr3.h.
typedef NRvector<Char> VecChar_O
Definition at line 516 of file nr3.h.
typedef NRvector<Char*> VecCharp
Definition at line 519 of file nr3.h.
typedef const NRvector<Char*> VecCharp_I
Definition at line 518 of file nr3.h.
typedef NRvector<Char*> VecCharp_IO
Definition at line 519 of file nr3.h.
typedef NRvector<Char*> VecCharp_O
Definition at line 519 of file nr3.h.
typedef NRvector<Complex> VecComplex
Definition at line 531 of file nr3.h.
typedef const NRvector<Complex> VecComplex_I
Definition at line 530 of file nr3.h.
typedef NRvector<Complex> VecComplex_IO
Definition at line 531 of file nr3.h.
typedef NRvector<Complex> VecComplex_O
Definition at line 531 of file nr3.h.
typedef NRvector<Doub> VecDoub
Definition at line 525 of file nr3.h.
typedef const NRvector<Doub> VecDoub_I
Definition at line 524 of file nr3.h.
typedef NRvector<Doub> VecDoub_IO
Definition at line 525 of file nr3.h.
typedef NRvector<Doub> VecDoub_O
Definition at line 525 of file nr3.h.
typedef NRvector<Doub*> VecDoubp
Definition at line 528 of file nr3.h.
typedef const NRvector<Doub*> VecDoubp_I
Definition at line 527 of file nr3.h.
typedef NRvector<Doub*> VecDoubp_IO
Definition at line 528 of file nr3.h.
typedef NRvector<Doub*> VecDoubp_O
Definition at line 528 of file nr3.h.
typedef NRvector<Int> VecInt
Definition at line 504 of file nr3.h.
typedef const NRvector<Int> VecInt_I
Definition at line 503 of file nr3.h.
typedef NRvector<Int> VecInt_IO
Definition at line 504 of file nr3.h.
typedef NRvector<Int> VecInt_O
Definition at line 504 of file nr3.h.
typedef NRvector<Llong> VecLlong
Definition at line 510 of file nr3.h.
typedef const NRvector<Llong> VecLlong_I
Definition at line 509 of file nr3.h.
typedef NRvector<Llong> VecLlong_IO
Definition at line 510 of file nr3.h.
typedef NRvector<Llong> VecLlong_O
Definition at line 510 of file nr3.h.
typedef NRvector<Uchar> VecUchar
Definition at line 522 of file nr3.h.
typedef const NRvector<Uchar> VecUchar_I
Definition at line 521 of file nr3.h.
typedef NRvector<Uchar> VecUchar_IO
Definition at line 522 of file nr3.h.
typedef NRvector<Uchar> VecUchar_O
Definition at line 522 of file nr3.h.
typedef NRvector<Uint> VecUint
Definition at line 507 of file nr3.h.
typedef const NRvector<Uint> VecUint_I
Definition at line 506 of file nr3.h.
typedef NRvector<Uint> VecUint_IO
Definition at line 507 of file nr3.h.
typedef NRvector<Uint> VecUint_O
Definition at line 507 of file nr3.h.
typedef NRvector<Ullong> VecUllong
Definition at line 513 of file nr3.h.
typedef const NRvector<Ullong> VecUllong_I
Definition at line 512 of file nr3.h.
typedef NRvector<Ullong> VecUllong_IO
Definition at line 513 of file nr3.h.
typedef NRvector<Ullong> VecUllong_O
Definition at line 513 of file nr3.h.
Function Documentation
template<class T > const T& MAX (const T & a, const T & b) [inline]
Definition at line 32 of file nr3.h.
float MAX (const float & a, const double & b) [inline]
Definition at line 38 of file nr3.h.
float MAX (const double & a, const float & b) [inline]
Definition at line 35 of file nr3.h.
template<class T > const T& MIN (const T & a, const T & b) [inline]
Definition at line 42 of file nr3.h.
float MIN (const double & a, const float & b) [inline]
Definition at line 45 of file nr3.h.
float MIN (const float & a, const double & b) [inline]
Definition at line 48 of file nr3.h.
float SIGN (const float & a, const double & b) [inline]
Definition at line 55 of file nr3.h.
float SIGN (const double & a, const float & b) [inline]
Definition at line 58 of file nr3.h.
template<class T > T SIGN (const T & a, const T & b) [inline]
Definition at line 52 of file nr3.h.
template<class T > T SQR (const T a) [inline]
Definition at line 29 of file nr3.h.
Referenced by Shep_interp::rad(), RBF_interp::rad(), RBF_inversemultiquadric::rbf(), RBF2_gauss::rbf(), RBF_gauss::rbf(), RBF_thinplate::rbf(), and RBF_multiquadric::rbf().
template<class T > void SWAP (T & a, T & b) [inline]
Definition at line 62 of file nr3.h.
Variable Documentation
const Doub NaN = numeric_limits<Doub>::quiet_NaN() [static]
Definition at line 494 of file nr3.h.