BTK: RBF_interp Struct Reference
RBF_interp Struct Reference
#include <interp_rbf.h>
Public Member Functions
Doub interp (VecDoub_I &pt)
Doub interp (VecDoub_I &pt)
Doub rad (const Doub *p1, const Doub *p2)
Doub rad (const Doub *p1, const Doub *p2)
RBF_interp (MatDoub_I &ptss, VecDoub_I &valss, RBF_fn &func, Bool nrbf=false)
RBF_interp (MatDoub_I &ptss, VecDoub_I &valss, RBF2_fn &func, Bool nrbf=false)
Public Attributes
Int dim
RBF_fn & fn
RBF2_fn & fn
Int n
Bool norm
const MatDoub & pts
const VecDoub & vals
VecDoub w
Detailed Description
Definition at line 9 of file interp_rbf.h.
Constructor & Destructor Documentation
RBF_interp::RBF_interp (MatDoub_I & ptss, VecDoub_I & valss, RBF2_fn & func, Bool nrbf = false) [inline]
Definition at line 36 of file interp_rbf.h.
References fn, n, norm, pts, RBF2_fn::rbf(), LUdcmp::solve(), vals, and w.
RBF_interp::RBF_interp (MatDoub_I & ptss, VecDoub_I & valss, RBF_fn & func, Bool nrbf = false) [inline]
Definition at line 13 of file interp_rbf_nr.h.
References fn, n, norm, pts, rad(), RBF2_fn::rbf(), LUdcmp::solve(), vals, and w.
Member Function Documentation
Doub RBF_interp::interp (VecDoub_I & pt) [inline]
Definition at line 84 of file interp_rbf.h.
References dim, fn, n, norm, pts, RBF2_fn::rbf(), NRvector< T >::size(), and w.
Doub RBF_interp::interp (VecDoub_I & pt) [inline]
Definition at line 32 of file interp_rbf_nr.h.
References dim, fn, n, norm, pts, rad(), RBF2_fn::rbf(), NRvector< T >::size(), and w.
Doub RBF_interp::rad (const Doub * p1, const Doub * p2) [inline]
Definition at line 43 of file interp_rbf_nr.h.
References dim, and SQR().
Doub RBF_interp::rad (const Doub * p1, const Doub * p2) [inline]
Definition at line 97 of file interp_rbf.h.
References dim, and SQR().
Referenced by interp(), and RBF_interp().
Member Data Documentation
Int RBF_interp::dim
Definition at line 10 of file interp_rbf.h.
Referenced by interp(), and rad().
RBF_fn& RBF_interp::fn
Definition at line 10 of file interp_rbf_nr.h.
RBF2_fn& RBF_interp::fn
Definition at line 14 of file interp_rbf.h.
Referenced by interp(), and RBF_interp().
Int RBF_interp::n
Definition at line 10 of file interp_rbf.h.
Referenced by interp(), and RBF_interp().
Bool RBF_interp::norm
Definition at line 15 of file interp_rbf.h.
Referenced by interp(), and RBF_interp().
const MatDoub & RBF_interp::pts
Definition at line 11 of file interp_rbf.h.
Referenced by interp(), and RBF_interp().
const VecDoub & RBF_interp::vals
Definition at line 12 of file interp_rbf.h.
Referenced by RBF_interp().
VecDoub RBF_interp::w
Definition at line 13 of file interp_rbf.h.
Referenced by interp(), and RBF_interp().
The documentation for this struct was generated from the following files:
interp_rbf.h
interp_rbf_nr.h