BTK: Shep_interp Struct Reference
Shep_interp Struct Reference
#include <interp_rbf.h>
Public Member Functions
Doub interp (VecDoub_I &pt)
Doub interp (VecDoub_I &pt)
Doub rad (const Doub *p1, const Doub *p2)
Doub rad (const Doub *p1, const Doub *p2)
Shep_interp (MatDoub_I &ptss, VecDoub_I &valss, Doub p=2.)
Shep_interp (MatDoub_I &ptss, VecDoub_I &valss, Doub p=2.)
Public Attributes
Int dim
Int n
Doub pneg
const MatDoub & pts
const VecDoub & vals
Detailed Description
Definition at line 162 of file interp_rbf.h.
Constructor & Destructor Documentation
Shep_interp::Shep_interp (MatDoub_I & ptss, VecDoub_I & valss, Doub p = 2.) [inline]
Definition at line 168 of file interp_rbf.h.
Shep_interp::Shep_interp (MatDoub_I & ptss, VecDoub_I & valss, Doub p = 2.) [inline]
Definition at line 78 of file interp_rbf_nr.h.
Member Function Documentation
Doub Shep_interp::interp (VecDoub_I & pt) [inline]
Definition at line 172 of file interp_rbf.h.
References dim, n, pneg, pts, rad(), NRvector< T >::size(), and vals.
Doub Shep_interp::interp (VecDoub_I & pt) [inline]
Definition at line 82 of file interp_rbf_nr.h.
References dim, n, pneg, pts, rad(), NRvector< T >::size(), and vals.
Doub Shep_interp::rad (const Doub * p1, const Doub * p2) [inline]
Definition at line 93 of file interp_rbf_nr.h.
References dim, and SQR().
Doub Shep_interp::rad (const Doub * p1, const Doub * p2) [inline]
Definition at line 183 of file interp_rbf.h.
References dim, and SQR().
Referenced by interp().
Member Data Documentation
Int Shep_interp::dim
Definition at line 163 of file interp_rbf.h.
Referenced by interp(), and rad().
Int Shep_interp::n
Definition at line 163 of file interp_rbf.h.
Referenced by interp().
Doub Shep_interp::pneg
Definition at line 166 of file interp_rbf.h.
Referenced by interp().
const MatDoub & Shep_interp::pts
Definition at line 164 of file interp_rbf.h.
Referenced by interp().
const VecDoub & Shep_interp::vals
Definition at line 165 of file interp_rbf.h.
Referenced by interp().
The documentation for this struct was generated from the following files:
interp_rbf.h
interp_rbf_nr.h